; ===============================================
; ESP8266 GPS UDP Tracker v1.1 - Public Release
; ===============================================

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.4m2m.ld

extra_scripts = post:combine_raw.py

lib_deps =
  ESP8266WiFi
  ESP8266WebServer
  LittleFS
  ArduinoJson
  EspSoftwareSerial

build_flags =
  -DVERSION="v1.1"
  -DDEBUG_DISABLED
